stages:
  - pull
  - compile


variables:
  OKMSG: "Стенд bivium_front успешно обновлен"
  FAILMSG: "Вниманией!Произошла ошибка при обновление стенда bivium_front"



pull master:
  stage: pull
  variables: 
    GIT_STRATEGY: none
  tags:
     - bivium_front
  script:
    - cd /var/www/nextjs
    - sudo git stash
    - sudo git fetch
    - sudo git checkout main
    - sudo git pull --rebase origin main
    - echo "OK"
  only:
    - main

compile: 
  stage: compile
  tags:
    - bivium_front
  script:
    - echo "Start Compile"
    - cd /var/www/nextjs
    - echo "Running npm install"
    - sudo npm install
    - if [ $? -ne 0 ]; then echo "npm install failed"; exit 1; fi
    - echo "Sleeping for 30 seconds"
    - sleep 30
    - echo "Running npm run build"
    - sudo npm run build
    - if [ $? -ne 0 ]; then echo "npm run build failed"; exit 1; fi
    - echo "Sleeping for 30 seconds"
    - sleep 30
    - echo "Compile OK"
  only:
    - main


