stages:
  - pull
  - compile


variables:
  OKMSG: "Стенд bivium_front успешно обновлен"
  FAILMSG: "Вниманией!Произошла ошибка при обновление стенда bivium_front"



pull master:
  stage: pull
  variables: 
    GIT_STRATEGY: none
  tags:
     - bivium_front
  script:
    - cd /var/www/nextjs
    - sudo git stash
    - sudo git fetch
    - sudo git checkout main
    - sudo git pull --rebase origin main
    - echo "OK"
  only:
    - main

compile:
  stage: compile
  tags:
    - bivium_front
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    - nvm install 15
    - nvm use 15
    - node -v
    - npm -v
  script:
    - echo "Start Compile"
    - cd /var/www/nextjs/
    - node -v
    - npm -v
    - npm install
    - sleep 10
    - npm run build
    - echo "Compile OK"
  only:
    - main


